### ISSUE TITLE
Include LICENSE and README in binary release zip/tar.gz

### ISSUE THREAD

**Issue by Gadgetoid** [32blit/32blit-boilerplate#2]
I think it makes sense for the LICENSE and README files to be included in releases.

That said, my repository has a screenshot in the README... maybe we need a "DIST.txt" or something (is there an established pattern for this?) with just a plain list of files to include when zipping up distributables.

**Comment by ahnlak** [comment]
Looks to be easy enough to just drop in a list of distributables to CMake's install chain. I'll add it in as soon as I work out how to fork my own repo ...

**Comment by ahnlak** [comment]
Done. All ready for your PR-merging magic!

**Comment by Gadgetoid** [comment]
It took me an embarresingly long time to figure out where the merge button had gone... this is an issue 😬 not a PR 😆

**Comment by ahnlak** [comment]
The PR is over there --> https://github.com/32blit/32blit-boilerplate/pull/5

(sorry, thought I'd linked it already!)

**Comment by Daft-Freak** [comment]
PR was merged (just a couple of years ago)
