### ISSUE TITLE
Windows SDL setup isn't needed any more

### ISSUE THREAD

**Issue by Daft-Freak** [32blit/32blit-boilerplate#3]
Since https://github.com/pimoroni/32blit-beta/pull/433 is merged, it should be possible to drop `ci/install_sdl_vs.sh` and the reference in `build.yml`.

**Comment by ahnlak** [comment]
Good point; seems to work fine without it so I will now try and work out how to merge a PR (if I can...)

**Comment by ahnlak** [comment]
Looks like I have a new place to create work for @Gadgetoid :)

**Comment by ahnlak** [comment]
Realised I can remove the script as well as the call to it, which should have come through in the PR too (if I did it right)
